#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
# redirection must be a “301 Moved Permanently”


sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default #add at line 30
sudo service nginx start
